* Release Changelog
** NEXT RELEASE
** release-2014-11-14.1
*** Fix: Fixed an issue for which multiple choice questions were not displayed correctly sometimes
*** Fix: Fixed the styling of inputs that are exponents, and increased the maximum characters to 3
** release-2014-11-13.1
*** Fix: Fix for the heart bar in chapter quiz, which on IE9 looked "cut"
*** Fix: Fixed an alignment bug in "Inloggen mislukt" in login application for IE9 users
*** Fix: Fix for an issue in publishing where you could not see prefix and suffix for inline inputs
*** Fix: Fix for styling of prefix and suffix for a line-input-field that were not visualized correctly
** release-2014-11-12.1:
*** Fix: Rewrote code related to input fields such that it's more mantainable and all in one place
*** New: Chapter quiz pages now show the title of the chapter they are related to
*** Fix: Fixed an issue with incorrect unlocking of chapter quiz + flow for chapter quizzes written more clearly in code
** release-2014-11-11.1:
*** New: Various fixes for inputs and new styling of content!
*** New: Redesign of the sidebar: now the "Explanation" and "Questions" toggling is in the header
*** Fix: Now reavealing an answer correctly triggers the stumbling block
*** Fix: Login form on iOS 8 position problems
*** New: Progress bar in chapter quiz window!
*** New: Updated computation of percentage for chapters in chapter list (now more closely reflect the status of the class)
*** New: When opening a chapter in the chapter-list report, you see which student have and have not finished the chapter
*** New: Show students & teachers in department and school editing screens
*** New: Updated favicon in all applications to reflect the new login
** release-2014-11-05.1
*** New: Chapter quizzes!
*** New: New logo in login and learning
*** Fix: Fixed a problem when publishing without an input width would result in an error
*** Fix: Height of sidenav is now appropriate, does not hide anymore content with small screens
*** New: Teachers can now report problems with usersnap
*** Fix: After you finish an entry quiz you are now correctly redirected to the chapter you're supposed to start from
*** Fix: preview of publishing questions render using learning styling
*** New: Sections can be searched from ID in the publishing application.
*** Fix: Excel report for teacher now correctly says that the percentages are about sections, not chapters
*** New: Students, upon completion of the entry quiz, now see how they did and where are they supposed to start learning.
** release-2014-10-23.1
*** Fix: Fixed styling bugs in chapter-list: now students with a stumbling block are shown correctly and there is a hint at what the warning sign means
** release-2014-10-22.2
*** New: Updated link texts for switching between Student & Teacher environments
** release-2014-10-22.1
*** Fix: Starting up time during deploy is shortened
*** Fix: Fixed a problem where teacher with a "/" in the class name would not see any report
*** Fix: Updating the sales status of a school without entering specifiying the number of licenses sets them to 0.
*** Fix: Testing with IE9 locally during development is restored
*** New: Publishing application now can check the HTML code inserted by the editors
*** New: Redesign of the "Chapter List" report: no more "semaphore" but progress bars and warning signs!
** release-2014-10-16.1
*** New: Attempt at fixing the modal not always showing when 5 questions in a row are answered correctly
*** New: Improved class navigation for teachers (classes sorted by name + class selection persists when changing report)
*** New: Moar cat gifs!!!1!!1!
** release-2014-10-14.1
*** New: Teachers can see the learning environment as if they were a student
*** New: Redesign of the teaching dashboard: more functional, way cooler
** release-2014-10-10.1
*** Fix: Fixed the bug in which 4 students were not able to access our site from edu route
*** Fix: Clearer explanation of the completion report with a note explaining which Meijerink are included
*** New: Improved teaching dashboard navigation by changing the dropdown and making nice URLs
*** New: Logging of all traffic to our applications
*** Ops: Passing of configuration parameters much easier for deployment
** release-2014-10-07.2
*** New: Teacher can see how much time students spend reading our explanations and answering questions
** release-2014-10-07.1
*** Fix: login issues
*** Fix: Answering incorrectly a question with IE9 gives feedback!
** release-2014-10-01.1
*** Ops: Parallel deployment re-enabled, deployment time significatively
** release-2014-09-30.2/1
*** Fix: Removal of <toev> HTML tags from the course material
*** Ops: During deployment, servers correctly report when they are ready to start working
** release-2014-09-29.2
*** Ops: Exception reporting for background threads
*** Ops: Cache heating on startup
*** New: Teacher can now export the progress of their classes to Excel
** release-2014-09.29.1
*** Fix: Data from imported student is correctly displayed in the "Chapter List" report
** release-2014-09.23.1
*** Ops: better exception reporting for JDBC errors
** release-2014-09.18.1
*** New: school-admin UX improvements
*** New: iPad layout improvments
