source 'https://rubygems.org'
ruby '2.1.2'

gem 'rails', '4.1.0'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',                    group: :development
gem 'bootstrap-sass'
gem 'haml-rails'
gem 'pg'
gem 'sendgrid'
gem 'zeroclipboard-rails'
gem 'acts_as_list'
gem 'httparty'
gem 'redis'
gem 'newrelic_rpm'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'nokogiri'
gem 'sanitize'
gem 'raygun4ruby'
gem "mini_magick"

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_21]
  gem 'guard-bundler'
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'rb-fchange', require: false
  gem 'rb-fsevent', require: false
  gem 'rb-inotify', require: false

  gem 'factory_girl_rails'
  gem 'rspec-rails', '>= 3.0.0.beta2'
  gem 'thin'
  gem 'guard-rails'
  gem 'guard-rspec'
end

group :test do
  gem 'capybara'
  gem 'phantomjs'
  gem 'poltergeist'
  gem 'database_cleaner'
  gem 'faker'
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'guard'
  gem 'therubyracer'
end
